import { Shield, AlertTriangle, Lock, Eye, HelpCircle } from 'lucide-react';

export default function About() {
  return (
    <div className="p-6 max-w-[900px] mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-bold" style={{ color: 'var(--color-text)' }}>
          About DrishtiSIF
        </h1>
        <p className="text-sm mt-1" style={{ color: 'var(--color-text-light)' }}>
          AI-Powered SIF Precursor Intelligence Platform
        </p>
      </div>

      <div className="space-y-6">
        <Section icon={<Shield size={18} />} title="What is SIF Precursor Screening?">
          <p>
            SIF (Serious Injury & Fatality) precursor screening is the process of analyzing safety reports —
            unsafe acts, unsafe conditions, near-misses, and incidents — to identify those that carry potential
            for serious injury or fatality. This differs from generic severity triage, which often ranks reports
            by what actually happened. SIF precursor screening looks at what <em>could have happened</em>:
            the exposure, the hazard energy, and whether the safety barrier held or failed.
          </p>
          <p className="mt-3">
            A near-miss where nobody was injured can still be a high-priority SIF precursor if the energy was
            present and the barrier failed. DrishtiSIF is designed to surface those reports so HSE teams can
            act before the next one becomes an incident.
          </p>
        </Section>

        <Section icon={<Lock size={18} />} title="IOGP Life-Saving Rules">
          <p>
            The IOGP (International Association of Oil & Gas Producers) Life-Saving Rules are a set of safety
            rules that address the activities most commonly associated with fatal incidents in the oil and gas
            industry. Each rule targets a specific type of high-energy hazard and the barrier that should prevent
            it. DrishtiSIF maps each report to the single most relevant Life-Saving Rule based on the detected
            hazard, activity, and barrier failure.
          </p>
          <p className="mt-3">
            The configured rules in this prototype include: Energy Isolation, Working at Height, Hot Work,
            Confined Space Entry, Lifting Operations, and Line of Fire.
          </p>
        </Section>

        <Section icon={<Eye size={18} />} title="How the Scoring Works">
          <p>
            The SIF Priority Score in this prototype is generated by a <strong>rule-based and keyword/phrase
            detection engine</strong>, not a trained machine-learning model. The engine detects safety signals
            in the free-text report — hazard keywords, barrier failure indicators, activity context — and
            combines them into a 0-100 priority score.
          </p>
          <p className="mt-3">
            This approach was chosen for a hackathon prototype because it is fully transparent, explainable,
            and runs locally without training data. A production system would likely combine this with
            embedding-based semantic similarity and a model trained on historical OIL report data.
          </p>
        </Section>

        <Section icon={<AlertTriangle size={18} />} title="Known Limitations">
          <ul className="list-disc pl-5 space-y-1.5">
            <li>Scoring is rule-based and has not been validated against historical OIL incident data.</li>
            <li>The system does not predict whether an accident will occur — it flags precursor patterns.</li>
            <li>Keyword-based detection may miss reports that use unfamiliar terminology or indirect language.</li>
            <li>The system assigns one primary Life-Saving Rule; complex multi-hazard scenarios may warrant additional review.</li>
            <li>All data in this prototype is synthetic and for demonstration purposes only.</li>
          </ul>
        </Section>

        <Section icon={<HelpCircle size={18} />} title="Important Note">
          <p className="font-medium" style={{ color: 'var(--color-text)' }}>
            This tool assists HSE review; it does not replace it.
          </p>
          <p className="mt-2">
            DrishtiSIF is an AI-assisted screening and decision support tool. All classifications, scores, and
            recommendations require validation by qualified HSE professionals. The system does not make final
            safety decisions.
          </p>
        </Section>
      </div>

      <div className="mt-8 p-4 rounded border" style={{ borderColor: 'var(--color-border)', backgroundColor: '#f8f9fb' }}>
        <p className="text-[12px]" style={{ color: 'var(--color-text-light)' }}>
          <strong style={{ color: 'var(--color-text)' }}>Demo Data:</strong> All reports in this prototype are
          synthetic and clearly labeled as DEMO / SYNTHETIC DATA. They do not represent real OIL incidents.
        </p>
      </div>

      <p className="text-[11px] mt-6" style={{ color: 'var(--color-text-light)' }}>
        AI-assisted screening for HSE review — not a final safety decision.
      </p>
    </div>
  );
}

function Section({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) {
  return (
    <div className="card p-5">
      <div className="flex items-center gap-2 mb-3">
        <div className="w-8 h-8 rounded flex items-center justify-center" style={{ backgroundColor: 'var(--color-info-bg)', color: 'var(--color-info)' }}>
          {icon}
        </div>
        <h2 className="text-[16px] font-semibold" style={{ color: 'var(--color-text)' }}>{title}</h2>
      </div>
      <div className="text-[13px] leading-relaxed pl-10" style={{ color: 'var(--color-text)' }}>
        {children}
      </div>
    </div>
  );
}
